[tox]
envlist = lint, unit, integration
skipsdist = true
requires = tox-uv

[testenv]
basepython = python3.12

[testenv:lint]
deps =
    ruff
    pyright
    codespell
    django>=5.2,<6
    djangorestframework>=3.15
    djangorestframework-api-key>=3.1
    drf-spectacular
    gunicorn
    psycopg[binary]>=3.3
    Jinja2
    whitenoise
    dj-database-url
    ops>=3,<4
commands =
    ruff check src tests
    ruff format --check src tests
    pyright src
    codespell src tests

[testenv:unit]
setenv =
    DJANGO_SETTINGS_MODULE = terrasquid.settings
    DATABASE_URL = sqlite:///terrasquid_test.db
deps =
    pytest
    pytest-django
    django>=5.2,<6
    djangorestframework>=3.15
    djangorestframework-api-key>=3.1
    drf-spectacular
    gunicorn
    Jinja2
    whitenoise
    dj-database-url
    ops[testing]
commands =
    pytest tests/unit -v {posargs}

[testenv:integration]
deps =
    jubilant
    pytest-jubilant
    requests
allowlist_externals =
    charmcraft
commands =
    charmcraft clean
    charmcraft pack
    pytest tests/integration -v {posargs}
