[tox]
envlist = lint, unit, integration
skipsdist = true

[testenv]
basepython = python3.12

[testenv:lint]
deps =
    ruff
    pyright
    codespell
    django>=5.2,<6
    djangorestframework>=3.15
    djangorestframework-api-key>=3.1
    drf-spectacular
    psycopg[binary]>=3.3
    Jinja2
    ops>=3,<4
commands =
    ruff check src tests
    ruff format --check src tests
    pyright src
    codespell src tests

[testenv:unit]
deps =
    pytest
    pytest-django
    django>=5.2,<6
    djangorestframework>=3.15
    djangorestframework-api-key>=3.1
    drf-spectacular
    psycopg[binary]>=3.3
    Jinja2
    ops[testing]
commands =
    pytest tests/unit -v {posargs}

[testenv:integration]
deps =
    jubilant
    pytest-jubilant
commands =
    pytest tests/integration -v {posargs}
