# Generated by Django 5.2.14 on 2026-05-13 10:51

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigVersion',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=0)),
                ('rendered_config', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=63)),
                ('key_prefix', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dst', models.TextField()),
                ('type', models.CharField(choices=[('ALLOW', 'ALLOW'), ('DENY', 'DENY'), ('CONNECT', 'CONNECT')], max_length=10)),
                ('ports', models.JSONField(blank=True, default=list, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DestinationGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=63)),
                ('key_prefix', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destinations', models.ManyToManyField(related_name='destination_groups', to='api.destinationconfig')),
            ],
            options={
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PortGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=63)),
                ('key_prefix', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ports', models.JSONField(default=list)),
            ],
            options={
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.AddField(
            model_name='destinationconfig',
            name='port_groups',
            field=models.ManyToManyField(blank=True, related_name='destination_configs', to='api.portgroup'),
        ),
        migrations.CreateModel(
            name='SourceACL',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=63)),
                ('key_prefix', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cidr', models.JSONField(default=list)),
            ],
            options={
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.CreateModel(
            name='SourceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=63)),
                ('key_prefix', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sources', models.ManyToManyField(related_name='source_groups', to='api.sourceacl')),
            ],
            options={
                'unique_together': {('service', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='destinationconfig',
            unique_together={('service', 'name')},
        ),
        migrations.CreateModel(
            name='ACLRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(max_length=255)),
                ('key_prefix', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=63, null=True)),
                ('priority', models.IntegerField(default=100)),
                ('dst', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acl_rules_dst', to='api.destinationconfig')),
                ('dst_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acl_rules_dst_group', to='api.destinationgroup')),
                ('src', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acl_rules_src', to='api.sourceacl')),
                ('src_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acl_rules_src_group', to='api.sourcegroup')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('src__isnull', True), ('src_group__isnull', False)), models.Q(('src__isnull', False), ('src_group__isnull', True)), _connector='OR'), name='acl_src_xor', violation_error_message='Exactly one of src or src_group must be set.'), models.CheckConstraint(condition=models.Q(models.Q(('dst__isnull', True), ('dst_group__isnull', False)), models.Q(('dst__isnull', False), ('dst_group__isnull', True)), _connector='OR'), name='acl_dst_xor', violation_error_message='Exactly one of dst or dst_group must be set.')],
                'unique_together': {('service', 'src', 'src_group', 'dst', 'dst_group')},
            },
        ),
    ]
