# Generated by Django 5.2.14 on 2026-07-29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_aclrule_dst_group_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="aclrule",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="destinationconfig",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sourceacl",
            name="comment",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
