# Generated by Django 5.2.12 on 2026-07-30

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_acl_comments"),
    ]

    operations = [
        migrations.CreateModel(
            name="DestinationGroup",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("service", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=63)),
                ("key_prefix", models.CharField(max_length=8)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("comment", models.CharField(blank=True, default="", max_length=255)),
                ("destinations", models.ManyToManyField(related_name="groups", to="api.destinationconfig")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("name",), name="unique_destination_group_name")],
            },
        ),
        migrations.AddField(
            model_name="aclrule",
            name="destination_groups",
            field=models.ManyToManyField(blank=True, related_name="rules", to="api.destinationgroup"),
        ),
    ]
